version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: docker-files/Dockerfile.backend
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ..
  #     dockerfile: docker-files/Dockerfile.frontend
  #   volumes:
  #     - ../frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: yarn dev
  #   depends_on:
  #     - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - frontend
      - backend

volumes:
  postgres_data:
