# Generated by Django 5.0.6 on 2024-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("store_manager", "Store Manager"),
                            ("product_manager", "Product Manager"),
                            ("order_manager", "Order Manager"),
                            ("customer_support", "Customer Support"),
                            ("finance_manager", "Finance Manager"),
                            ("marketing_specialist", "Marketing Specialist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_users",
            },
        ),
    ]
